import type { Metadata } from 'next';

import { Oswald } from 'next/font/google';

import localFont from 'next/font/local';

import { Header } from '@/components/layout/header';
import { Footer } from '@/components/layout/footer';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 200 300 900',
});

const osvaldo = Oswald({
  subsets: ['latin'],
  variable: '--font-osvaldo',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${osvaldo.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
